# Generated by Django 4.2.4 on 2023-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='release_date',
            new_name='date',
        ),
    ]
